### ISSUE TITLE
QLIE filter broken

### ISSUE THREAD

**Issue by JackOfBadTrades** [marcussacana/AIO#1]
[This script](https://files.catbox.moe/aqlghh.zip), which is from Walkure Romanze More&More, somehow breaks the QLIE filter. It doesn't extract it and it [throws an error](https://files.catbox.moe/hzae0d.jpg).
All other scripts got extracted fine, it's just this one that's giving me trouble.
I tried to take a look inside, but I didn't really see anything that raises an eye. Maybe you can get better results with a debugger.

**Comment by JackOfBadTrades** [comment]
Remember me? And this bug?

Well, I tried working through the problematic script line by line and found out that it's THIS piece of code that's making your tool crash:
```
ber_005_00_noe1006,ノエル,「そういうこと。私たちが少し早く来すぎただけよ」
file4:Aパターン/,file5:腕1/2,file6:02喜2,show:false
^chara02,file4:Aパターン/,file5:腕1/,file6:02喜2,show:false
```
To be more specific, it's the 2nd line (Line 1285 in the original script) that triggers the crash. When I delete it, the tool extracts the script just fine.
Notice how it looks suspiciously similar to the 3rd line. Just guessing here, but it appears this line was made in error by the developers of the game, and *not a bug of your tool at all!*

At this point I'd consider the issue fixed, but I'm not an actual programmer myself so I'd like your opinion first.

**Comment by marcussacana** [comment]
qlie script syntax is a pain to understand, the problem is that the QLIE filter detect lines by commands that does not starts with ^ and have 3 division by comma, and that line meets this two conditions, and that make the tool crash it.
not sure what can be done to ignore line like this one, maybe if I find all parts of the line that contain `:`?

**Comment by marcussacana** [comment]
checks if the game still works if you put ^ in the begin of that line

**Comment by JackOfBadTrades** [comment]
Yeah just confirmed in game. Adding a ^ doesn't do anything. Removing the line itself (with CR LF) doesn't do anything either.

Yep, just a bug from the devs and the line can be removed safely. Problem solved!
